### PR TITLE
Automatic import & validation with Ghostfolio

### LINKED ISSUE #62: Add functionality to automatically validate JSON and upload to Ghostfolio
Ghostfolio offers endpoints to automatically validate and upload activities.

There should be two settings that allows users to automatically upload the converted JSON to Ghostfolio. This can be done in two steps. Firstly, validate the JSON. And then also import automatically.

This will be an experimental feature, because there is no human oversight  for checking duplicate transactions.

### PR DESCRIPTION
**Pull request by dickwolff**
## Added

- Automatic validation & import of the generated JSON file.

## Checklist

- [x] Added relevant changes to README (if applicable)
- [ ] ~Added relevant test(s)~
- [x] Updated GitVersion file

## Related issue (if applicable)

Fixes #62

### CODE REVIEW

**Comment by dickwolff** [comment]
Resolves #62

**Comment by dickwolff** [comment]
@lildude Would you be willing to test this feature for me? You can pull the latest image and set the corresponding variables. They are listed in the readme.

**Comment by lildude** [comment]
Wow!! This is nice and works a treat... once I fixed the [imports](https://github.com/dickwolff/Export-To-Ghostfolio/pull/67)

**Comment by dickwolff** [comment]
I put out a temporary fix (#66 ) an hour ago or so. There is a know issue with `tsx` that causes the imports to fail in `tsx` v4.9.1. Still works in 4.9.0 so that is now a workaround. 

I'm following the issue with tsx and will release a fix when that is resolved.

**Pull request merged**
