### PR TITLE
Add eToro converter (and some other improvements)

### PR DESCRIPTION
**Pull request by dickwolff**
## Added

- ✨ New broker: eToro
- 🏗️ Improved testability of the converters by allowing the Yahoo Finance service to be provided via dependency injection
- 📈 Improved test coverage of Trading 212 converter 
 
## Fixes

- 🐛 Fixed the Schwab converter as this was not working due to some changes from last week
- 🐛 Added some more language specific rules for DEGIRO (ignore & platform fees)

### CODE REVIEW

**Comment by dickwolff** [comment]
@semiBE Here is a [first draft](https://github.com/dickwolff/Export-To-Ghostfolio/tree/feature/Etoro-Converter) of an Etoro converter. The example you provided in #25 is processed correctly.

Can you verify if the data is correct and if there are any other issues?

Whenever you are satisfied with it, can you provide me with instructions how to export data from Etoro (and convert xsls to CSV) so I can add it to the readme in the repository? Thanks!!

**Comment by semiBE** [comment]
For eToro you need to select the "Portfolio" section on the left then go to the top of the page where you see "My Portfolio" and click on the arrow facing down and select "History" then you click on the icon on the extreme right which looks like 3 vertical bars and a wheel on top (no clue about the meaning). There you select "Account statement". In the next page you choose the dates of interest and click create. In the next page you click on the xlsx icon on the top right to download the xlsx file. Afterwards you delete all the tabs from the file but the "Account Activity" and convert the file to a comma separated values file (.csv)

**Comment by semiBE** [comment]
I tested with the sample file and it looks like it's recognized somewhat differently than eToro. Here the log:
```
2024-02-08T19:19:23.989719371Z     at Object.readFileSync (node:fs:453:20)
2024-02-08T19:19:23.989723701Z     at SchwabConverter.processFileContents (/app/src/converters/schwabConverter.ts:30:28)
2024-02-08T19:19:23.989727891Z     at SchwabConverter.readAndProcessFile (/app/src/converters/abstractconverter.ts:34:14)
2024-02-08T19:19:23.989733549Z     at createAndRunConverter (/app/src/converter.ts:25:15)
2024-02-08T19:19:23.989739695Z     at FSWatcher.<anonymous> (/app/src/watcher.ts:47:30)
2024-02-08T19:19:23.989746819Z     at FSWatcher.emit (node:events:518:28)
2024-02-08T19:19:23.989751079Z     at FSWatcher.emit (node:domain:488:12)
2024-02-08T19:19:23.989755340Z     at FSWatcher.emitWithAll (/app/node_modules/chokidar/index.js:540:8)
2024-02-08T19:19:23.989759600Z     at FSWatcher._emit (/app/node_modules/chokidar/index.js:632:8)
2024-02-08T19:19:23.989763860Z     at NodeFsHandler._handleFile (/app/node_modules/chokidar/lib/nodefs-handler.js:400:14) {
2024-02-08T19:19:23.989768540Z   errno: -2,
2024-02-08T19:19:23.989772381Z   code: 'ENOENT',
2024-02-08T19:19:23.989776572Z   syscall: 'open',
2024-02-08T19:19:23.989780902Z   path: 'Date,Type,Details,Amount,Units,Realized Equity Change,Realized Equity,Balance,Position ID,Asset type,NWA\n' +
```

**Comment by dickwolff** [comment]
Did you try it with the Docker image? Because I have not published a new version of the image yet that has eToro support. So that would explain why it has run with Schwab. Currently you can only run it locally.

**Comment by dickwolff** [comment]
@semiBE I have created a beta image [here](https://hub.docker.com/layers/dickwolff/export-to-ghostfolio/0.4.0-beta/images/sha256-40611325599eefa250a37d6060f9ebef86632f586bea871a003a9c4cc845857b?context=explore) (tag 0.4.0-beta). This now should work with eToro file watcher (and also has some more improvements for the other converters).

**Comment by dickwolff** [comment]
Fixes request from #25

**Comment by semiBE** [comment]
> Did you try it with the Docker image? Because I have not published a new version of the image yet that has eToro support. So that would explain why it has run with Schwab. Currently you can only run it locally.

Indeed I tested it in Docker, I`ll check the beta image!

**Pull request merged**
