### PR TITLE
Mock yahoo finance service during testing

### PR DESCRIPTION
**Pull request by dickwolff**
## Changed

- Refactored YahooFinanceService as SecurityService, allowing yahoo-finance2 code-behind to be mocked during testing
- Added Yahoo Finance Service mock, relevant testdata files (json) and added it to all the tests

## Checklist

- [x] Added relevant changes to README (if applicable)
- [x] Added relevant test(s)
- [x] Updated GitVersion file

### CODE REVIEW

**Comment by dickwolff** [comment]
Fixes #60

**Comment by dickwolff** [comment]
Need to add some instructions on how to add new testdata to the mock.

**Comment by dickwolff** [comment]
@lildude I found an issue in the Freetrade converter where it seemed like it didn't process dividends correctly. I believe the result file of the main-branch version of the tool would not be accepted by Ghostfolio. I think I fixed that.

**Comment by lildude** [comment]
Whoops. I thought I didn't need that so removed it instead of moving it. Good catch. Thanks.

**Pull request merged**
