### PR TITLE
Rewrite DEGIRO converter

### LINKED ISSUE #19: Improve readability of DEGIRO converter
The DEGIRO converter is not digestable, so needs to be rewritten. Also some flexibility towards line order should be in order.

### PR DESCRIPTION
**Pull request by dickwolff**
Complete rewrite of the DEGIRO converter, which is more flexible regarding the order in which lines are exported by DEGIRO.

Also add support for yearly product fees.

Fixes #19

### CODE REVIEW

**Review by Joren-vanGoethem — APPROVED** [review]
just took a quick look at this since i also use degiro and was interested. looks good but the one massive method should probably be split up in smaller methods just for readability and maintainability.

**Comment by dickwolff** [comment]
This is still a work in progress and in my opinion an improvement over the current `main` code. I am in talks with another user that had some issues that I hope to resolve with these changes. After which I will merge this and then do another step in improving readability.

Im also planning some automated testing in #16 so everything becomes more predictable and whenever I need to change something in the future I have some guarantee it keeps working and don't have to do manual regression (which I what I do currently).

**Comment by Joren-vanGoethem** [comment]
are you also plannint to support dividends in your new converter? currently it only does Buy and Sell orders

**Comment by dickwolff** [comment]
This version supports [fees](https://github.com/dickwolff/Export-To-Ghostfolio/blob/b0e5ef8e7470326f5f031547c01bf911b97f3eb9/src/converters/degiroConverter.ts#L70) (eg. Exchange fee), [buy & sell](https://github.com/dickwolff/Export-To-Ghostfolio/blob/b0e5ef8e7470326f5f031547c01bf911b97f3eb9/src/converters/degiroConverter.ts#L206) and [also dividend](https://github.com/dickwolff/Export-To-Ghostfolio/blob/b0e5ef8e7470326f5f031547c01bf911b97f3eb9/src/converters/degiroConverter.ts#L265).

**Comment by Joren-vanGoethem** [comment]
i tried running it just now but dividends are not included in the export json.
also the fees seem to have some rounding on them? they are almost all 1, 2 or 0
one fee is 4.9 which is weird because this makes me wonder why the others are rounded

**Comment by Joren-vanGoethem** [comment]
i guess you already use degiro but if you want my export, which is pretty big i can send it to you. it also had a few ISIN numbers it didn't find
Target for example which is think is quite weird because target isn't exactly a small or unknown company for yahoo finance

**Comment by dickwolff** [comment]
I do use DEGIRO myself yes, however if you could share (a portion) of your export that would be helpful, as I can also check the specific issues you mentioned about fees and perhaps find a reason why certain isin numbers aren't found.

**Comment by Joren-vanGoethem** [comment]
[Account.csv](https://github.com/dickwolff/Export-To-Ghostfolio/files/13822795/Account.csv)

also one peculiar thing that happened recently, you might see at the top of the csv file there is some weird stuff going on with dividends
this was a mistake on Degiro's side. they messed up my mcdonalds dividends (they fixed it by adding more dividend transactions)
but i wonder how your converted would react to this since i might not be the only one who this has happened to
image

i'm also interested in helping on this of course
perhaps tomorrow evening i'll have some time to spare and look at the code in more detail

**Comment by Joren-vanGoethem** [comment]
i just saw that my export from degiro contains dutch csv headers, i can't find any setting to change this
do you know where i can change this?

**Comment by dickwolff** [comment]
I believe that is a DEGIRO thing, exporting in your current locale. However it should not matter what language the header is, as the header are always on the same position, no matter which language, so they can be mapped easily.

I havent had time to look at the dividend issue last weekend due to some personal things but will look into it tomorrow or friday.

**Comment by dickwolff** [comment]
@Joren-vanGoethem I ran your export file through the tool and found some more fields that should be skipped. I wanted to look at the file that would be generated, but I am currently rate limited by Yahoo Finance, 

EDIT: The rate limit is gone so I was able to run the tool once more. See the [ghostfolio-degiro.json](https://github.com/dickwolff/Export-To-Ghostfolio/files/13878968/ghostfolio-degiro.json)

It does contain dividend records for me, however fees are empty as you also stated. Will look into those now.

**Comment by dickwolff** [comment]
@dascgit I have reworked the DEGIRO converter in this changeset, which also changes the way dividend records are processed. If I remember correctly, your exports were in Germen, right? Could you give me the description for a "dividend tax" fee record, e.g. "Dividenbelasting" in Dutch? That way I can add it to the control that checks for the record and thay way dividend tax records from a German language are also processed correctly. Thanks a bunch!

**Comment by dascgit** [comment]
> onverter in this changeset, which also changes the way dividend records are processed. If I remember correctly, your exports were in Germen, right? Could you give me the description for a "dividend tax" fee record, e.g. "Dividenbelasting" in Dutch? That way I can add it to the control that checks for the record and thay way dividend tax records from a German language are also processed correctly. Thanks a bunch!

Sorry @dickwolff for my late response. I no longer have a degiro account and I cant provide the informations.

**Comment by dickwolff** [comment]
No worries, thanks for your response though!

**Pull request merged**
